version: '3.8'

services:
   postgres:
     image: postgres:latest
     container_name: RChat.Db
     environment:
       POSTGRES_DB: "RChat"
       POSTGRES_USER: "postgres"
       POSTGRES_PASSWORD: "postgres"
     ports:
       - "5200:5432"